name: Déployer sur GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le code
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installer les dépendances
        run: |
          npm install

      - name: Compiler l'application
        run: |
          npm run build

      - name: Déboguer la sortie de build
        run: |
          ls -la ./build

      - name: Téléverser les artefacts de build
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./build

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
